import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import './globals.css';
import 'react-toastify/dist/ReactToastify.css';

import Header from '@/app/components/header/Header';
import { ToastContainer } from 'react-toastify';

const montSans = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montSans.variable} antialiased`}>
        <ToastContainer position="top-right" autoClose={3000} />
        <Header />
        {children}
      </body>
    </html>
  );
}
